# Flight Forecast with Google Flights

`Authors:` Sarah Beltran, Monica Ibarra & Michelle

`Date:` 08/05/2026

---

## Introduction

In [1]:
import pandas as pd

In [6]:
df = pd.read_csv('data/avia_par_uk__custom_21385003_linear_2_0.csv')
df.head()

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,freq,Time frequency,unit,Unit of measure,tra_meas,Traffic and transport measurement,airp_pr,Airport pairs (routes),TIME_PERIOD,Time,OBS_VALUE,Observation value,OBS_FLAG,Observation status (Flag) V2 structure,CONF_STATUS,Confidentiality status (flag)
0,dataflow,ESTAT:AVIA_PAR_UK(1.0),Air passenger transport routes between partner...,M,Monthly,PAS,Passenger,PAS_BRD,Passengers on board,UK_EGAA_UK_EGGW,BELFAST/ALDERGROVE airport - LONDON LUTON airport,1998-09,NaN,6075,NaN,NaN,NaN,NaN,NaN
1,dataflow,ESTAT:AVIA_PAR_UK(1.0),Air passenger transport routes between partner...,M,Monthly,PAS,Passenger,PAS_BRD,Passengers on board,UK_EGAA_UK_EGGW,BELFAST/ALDERGROVE airport - LONDON LUTON airport,1998-10,NaN,12941,NaN,NaN,NaN,NaN,NaN
2,dataflow,ESTAT:AVIA_PAR_UK(1.0),Air passenger transport routes between partner...,M,Monthly,PAS,Passenger,PAS_BRD,Passengers on board,UK_EGAA_UK_EGGW,BELFAST/ALDERGROVE airport - LONDON LUTON airport,1998-11,NaN,15234,NaN,NaN,NaN,NaN,NaN
3,dataflow,ESTAT:AVIA_PAR_UK(1.0),Air passenger transport routes between partner...,M,Monthly,PAS,Passenger,PAS_BRD,Passengers on board,UK_EGAA_UK_EGGW,BELFAST/ALDERGROVE airport - LONDON LUTON airport,1998-12,NaN,15366,NaN,NaN,NaN,NaN,NaN
4,dataflow,ESTAT:AVIA_PAR_UK(1.0),Air passenger transport routes between partner...,M,Monthly,PAS,Passenger,PAS_BRD,Passengers on board,UK_EGAA_UK_EGGW,BELFAST/ALDERGROVE airport - LONDON LUTON airport,1999-01,NaN,15285,NaN,NaN,NaN,NaN,NaN

In [7]:
df = df.drop(columns=[
    "Time",
    "Observation value",
    "OBS_FLAG",
    "Observation status (Flag) V2 structure",
    "CONF_STATUS",
    "Confidentiality status (flag)"
])
df.head()

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,freq,Time frequency,unit,Unit of measure,tra_meas,Traffic and transport measurement,airp_pr,Airport pairs (routes),TIME_PERIOD,OBS_VALUE
0,dataflow,ESTAT:AVIA_PAR_UK(1.0),Air passenger transport routes between partner...,M,Monthly,PAS,Passenger,PAS_BRD,Passengers on board,UK_EGAA_UK_EGGW,BELFAST/ALDERGROVE airport - LONDON LUTON airport,1998-09,6075
1,dataflow,ESTAT:AVIA_PAR_UK(1.0),Air passenger transport routes between partner...,M,Monthly,PAS,Passenger,PAS_BRD,Passengers on board,UK_EGAA_UK_EGGW,BELFAST/ALDERGROVE airport - LONDON LUTON airport,1998-10,12941
2,dataflow,ESTAT:AVIA_PAR_UK(1.0),Air passenger transport routes between partner...,M,Monthly,PAS,Passenger,PAS_BRD,Passengers on board,UK_EGAA_UK_EGGW,BELFAST/ALDERGROVE airport - LONDON LUTON airport,1998-11,15234
3,dataflow,ESTAT:AVIA_PAR_UK(1.0),Air passenger transport routes between partner...,M,Monthly,PAS,Passenger,PAS_BRD,Passengers on board,UK_EGAA_UK_EGGW,BELFAST/ALDERGROVE airport - LONDON LUTON airport,1998-12,15366
4,dataflow,ESTAT:AVIA_PAR_UK(1.0),Air passenger transport routes between partner...,M,Monthly,PAS,Passenger,PAS_BRD,Passengers on board,UK_EGAA_UK_EGGW,BELFAST/ALDERGROVE airport - LONDON LUTON airport,1999-01,15285